services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/dev-todo.me/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/dev-todo.me/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    depends_on:
      - client
      - server
    networks:
      - todo-network
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
      args:
        - VITE_API_URL=/api/todos
    expose:
      - "80"
    depends_on:
      - server
    networks:
      - todo-network
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    expose:
      - "5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=todo_db
      - DB_LOGGING=false
    depends_on:
      db:
        condition: service_healthy
    networks:
      - todo-network
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todo_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d todo_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - todo-network
    restart: unless-stopped

networks:
  todo-network:
    driver: bridge

volumes:
  db_data:
    driver: local